version: '2.3'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - .data:/data/db
    # environment:
    #   - name=value
    env_file:
      - ./env/mongo.env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 80:80

    volumes:
      - ./backend:/app
      - logs:/app/logs
      - node_modules:/app/node_modules

    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    command: npm start
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend 
    volumes:
      - ./frontend/src:/app/src 

volumes:
  data:
  logs:
  node_modules:

networks:
  goals-net:
    driver: bridge