version: '3.8'

services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
    networks:
      - goals-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend/logs:/app/logs
      - logs:/app/logs
      - node_modules:/app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    command: npm start
    networks:
      - goals-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    networks:
      - goals-net

volumes:
  data:
  logs:
  node_modules:

networks:
  goals-net:
    driver: bridge
