version: '2.3'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - .data:/data/db
    # environment:
    #   - name=value
    env_file:
      - ./env/mongo.env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./backend:/app
      - logs:/app/logs
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend  

volumes:
- data:/app/data

networks:
  goals-net:
    driver: bridge